### ISSUE TITLE
in_service variable in speed_price_verizon.csv

### ISSUE THREAD

**Issue by ghost** [the-markup/investigation-isp#2]
Hello,

Can you please tell me what the Boolean in_service variable in the speed_price_verizon.csv means?

Thanks!

**Comment by yinleon** [comment]
That field is pulled from here:
https://github.com/the-markup/investigation-isp/blob/main/notebooks/parsers.py#L364

We did not use it in our analysis, so I can't with any authority describe what it means.
You're welcome to check out the raw JSON, and try to make your own interpretation.

I am considering removing it from the file. 
Do you think it's useful or distracting?

**Comment by ghost** [comment]
Thanks for the response. I don't think it's a useful variable without knowing it's meaning.
